# Generated by Django 3.1.1 on 2020-09-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='person',
            new_name='calculator',
        ),
    ]
